extends: [a]
ignorePatterns:
  - /next.config.js
  - /next-env.d.ts
rules:
  sort-imports:
    - error
    - ignoreCase: true
      ignoreDeclarationSort: true # -> import/order
  import/order:
  - error
  - alphabetize:
      order: asc
      caseInsensitive: true
